use crate::schema::{
    create_index, create_schema_statements, drop_schema_statements, Column, DBType, Index,
    PrimaryKey, Schema, Table,
};

#[test]
fn builds_postgres_schema_sql_for_table_and_indexes() {
    let schema = Schema {
        name: "inventory".to_string(),
        tables: vec![Table {
            name: "items".to_string(),
            columns: vec![
                Column {
                    name: "id".to_string(),
                    data_type: DBType::BigInt,
                    nullable: false,
                    default: Some("GENERATED BY DEFAULT AS IDENTITY".to_string()),
                },
                Column {
                    name: "name".to_string(),
                    data_type: DBType::VarChar850,
                    nullable: false,
                    default: Some("''".to_string()),
                },
                Column {
                    name: "description".to_string(),
                    data_type: DBType::Text,
                    nullable: true,
                    default: None,
                },
            ],
            primary_key: PrimaryKey {
                name: "pk_items".to_string(),
                columns: vec!["id".to_string()],
            },
            indexes: vec![
                Index {
                    name: "idx_items_name".to_string(),
                    columns: vec!["name".to_string()],
                    unique: false,
                },
            ],
        }],
    };

    let sql = create_schema_statements(&schema);

    assert_eq!(sql.len(), 4);
    assert_eq!(
        sql[0].sql,
        "CREATE SCHEMA IF NOT EXISTS inventory"
    );
    assert_eq!(
        sql[1].sql,
        "CREATE TABLE IF NOT EXISTS inventory.items (\n  id BIGINT NOT NULL DEFAULT GENERATED BY DEFAULT AS IDENTITY,\n  name VARCHAR(850) NOT NULL DEFAULT '',\n  description TEXT\n)"
    );
    assert_eq!(
        sql[2].sql,
        "ALTER TABLE inventory.items ADD CONSTRAINT pk_items PRIMARY KEY (id)"
    );
    assert_eq!(
        sql[3].sql,
        "CREATE INDEX IF NOT EXISTS inventory.idx_items_name ON inventory.items (name)"
    );
}

#[test]
fn builds_unique_index_sql() {
    let table = Table {
        name: "categories".to_string(),
        columns: Vec::new(),
        primary_key: PrimaryKey {
            name: "pk_categories".to_string(),
            columns: vec!["id".to_string()],
        },
        indexes: vec![Index {
            name: "uq_categories_name".to_string(),
            columns: vec!["name".to_string()],
            unique: true,
        }],
    };
    let schema = Schema {
        name: "inventory".to_string(),
        tables: vec![table.clone()],
    };

    let sql = create_index(&schema, &table, &table.indexes[0]);

    assert_eq!(
        sql.sql,
        "CREATE UNIQUE INDEX IF NOT EXISTS inventory.uq_categories_name ON inventory.categories (name)"
    );
}

#[test]
fn builds_drop_schema_sql_for_table_and_indexes() {
    let schema = Schema {
        name: "inventory".to_string(),
        tables: vec![Table {
            name: "items".to_string(),
            columns: Vec::new(),
            primary_key: PrimaryKey {
                name: "pk_items".to_string(),
                columns: vec!["id".to_string()],
            },
            indexes: vec![Index {
                name: "idx_items_name".to_string(),
                columns: vec!["name".to_string()],
                unique: false,
            }],
        }],
    };

    let sql = drop_schema_statements(&schema);

    assert_eq!(sql.len(), 4);
    assert_eq!(sql[0].sql, "DROP INDEX IF EXISTS inventory.idx_items_name");
    assert_eq!(
        sql[1].sql,
        "ALTER TABLE inventory.items DROP CONSTRAINT IF EXISTS pk_items"
    );
    assert_eq!(sql[2].sql, "DROP TABLE IF EXISTS inventory.items");
    assert_eq!(sql[3].sql, "DROP SCHEMA IF EXISTS inventory");
}
