use std::path::Path;

use sqlx::PgPool;

use crate::model::{ModelRegistry, ParsedModel};
use crate::runtime::contracts::OWNED_ENTITY_TYPE;

pub async fn ensure_schema(db: &PgPool, model_dir: &Path) -> Result<(), sqlx::Error> {
    let registry = ModelRegistry::load_from_dir(model_dir)
        .map_err(|err| sqlx::Error::Protocol(format!("failed to load model registry: {err}")))?;

    let mut entity_names: Vec<_> = registry.entities().collect();
    entity_names.sort_unstable();

    for entity_name in entity_names {
        let parsed = registry
            .get(entity_name)
            .expect("entity returned from registry iterator should exist");
        ensure_table_for_model(db, parsed).await?;
    }

    Ok(())
}

async fn ensure_table_for_model(db: &PgPool, parsed: &ParsedModel) -> Result<(), sqlx::Error> {
    let table = &parsed.schema.tables[0];
    let create_sql = create_table_statement(parsed);
    sqlx::query(&create_sql).execute(db).await?;

    for column in table.columns.iter().skip(1) {
        let alter_sql = format!(
            "ALTER TABLE {} ADD COLUMN IF NOT EXISTS {} {}{}{}",
            parsed.mapping.table_name,
            column.name,
            column.data_type.sql(),
            if column.nullable { "" } else { " NOT NULL" },
            column
                .default
                .as_ref()
                .map(|default| format!(" DEFAULT {default}"))
                .unwrap_or_default()
        );
        sqlx::query(&alter_sql).execute(db).await?;
    }

    for system_column in owned_system_columns(parsed) {
        sqlx::query(&format!(
            "ALTER TABLE {} ADD COLUMN IF NOT EXISTS {}",
            parsed.mapping.table_name, system_column
        ))
        .execute(db)
        .await?;
    }

    for index in &table.indexes {
        let index_sql = format!(
            "CREATE {}INDEX IF NOT EXISTS {} ON {} ({})",
            if index.unique { "UNIQUE " } else { "" },
            index.name,
            parsed.mapping.table_name,
            index.columns.iter().cloned().collect::<Vec<_>>().join(", ")
        );
        sqlx::query(&index_sql).execute(db).await?;
    }

    if parsed.model.entity.name == OWNED_ENTITY_TYPE {
        sqlx::query(&format!(
            "CREATE INDEX IF NOT EXISTS idx_{}_ownership ON {} (owner_service, entity_type)",
            parsed.mapping.table_name, parsed.mapping.table_name
        ))
        .execute(db)
        .await?;
    }

    Ok(())
}

fn create_table_statement(parsed: &ParsedModel) -> String {
    let table = &parsed.schema.tables[0];
    let columns = table
        .columns
        .iter()
        .map(|column| {
            let mut sql = format!("{} {}", column.name, column.data_type.sql());

            if let Some(default) = &column.default {
                if default == "GENERATED BY DEFAULT AS IDENTITY" {
                    sql.push_str(&format!(" {default}"));
                } else {
                    if !column.nullable {
                        sql.push_str(" NOT NULL");
                    }
                    sql.push_str(&format!(" DEFAULT {default}"));
                    return sql;
                }
            }

            if !column.nullable {
                sql.push_str(" NOT NULL");
            }
            sql
        })
        .chain(owned_system_columns(parsed).into_iter().map(str::to_string))
        .chain(std::iter::once(format!(
            "CONSTRAINT {} PRIMARY KEY ({})",
            table.primary_key.name,
            table.primary_key.columns.iter().cloned().collect::<Vec<_>>().join(", ")
        )))
        .collect::<Vec<_>>()
        .join(",\n  ");

    format!(
        "CREATE TABLE IF NOT EXISTS {} (\n  {}\n)",
        parsed.mapping.table_name, columns
    )
}

fn owned_system_columns(parsed: &ParsedModel) -> Vec<&'static str> {
    if parsed.model.entity.name == OWNED_ENTITY_TYPE {
        vec![
            "owner_service TEXT NOT NULL DEFAULT 'inventory-core'",
            "entity_type TEXT NOT NULL DEFAULT 'item'",
        ]
    } else {
        Vec::new()
    }
}

#[cfg(test)]
mod tests {
    use super::create_table_statement;
    use crate::model::parse_model;

    #[test]
    fn builds_model_driven_create_table_statement() {
        let parsed = parse_model(
            r#"
format_version = 1
version = "1.0.0"

[entity]
name = "item"
table = "inventory_items"
fields = [
  { name = "name", type = "label", required = true, default = "", indexed = true },
  { name = "quantity", type = "integer", required = true, default = 0, conflict_resolution = { mode = "increment" } }
]
"#,
        )
        .expect("model should parse");

        let sql = create_table_statement(&parsed);

        assert!(sql.contains("CREATE TABLE IF NOT EXISTS inventory_items"));
        assert!(sql.contains("id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL"));
        assert!(sql.contains("name VARCHAR(64) NOT NULL DEFAULT ''"));
        assert!(sql.contains("quantity BIGINT NOT NULL DEFAULT 0"));
        assert!(sql.contains("owner_service TEXT NOT NULL DEFAULT 'inventory-core'"));
        assert!(sql.contains("entity_type TEXT NOT NULL DEFAULT 'item'"));
        assert!(sql.contains("CONSTRAINT pk_inventory_items PRIMARY KEY (id)"));
    }
}
