use crate::schema::{
    create_index, create_schema_statements, drop_schema_statements, persistence_catalog, DataType,
    Schema, Table,
};

#[test]
fn builds_postgres_schema_sql_for_table_and_indexes() {
    let schema = Schema::new("inventory").table(
        Table::new("items")
            .column_default("id", DataType::BigInt, "GENERATED BY DEFAULT AS IDENTITY")
            .column_default("name", DataType::VarChar850, "''")
            .column_nullable("description", DataType::Text)
            .primary_key("pk_items", ["id"])
            .index("idx_items_name", ["name"]),
    );

    let sql = create_schema_statements(&schema);

    assert_eq!(sql.len(), 4);
    assert_eq!(sql[0].sql, "CREATE SCHEMA IF NOT EXISTS inventory");
    assert_eq!(
        sql[1].sql,
        "CREATE TABLE IF NOT EXISTS inventory.items (\n  id BIGINT NOT NULL DEFAULT GENERATED BY DEFAULT AS IDENTITY,\n  name VARCHAR(850) NOT NULL DEFAULT '',\n  description TEXT\n)"
    );
    assert_eq!(
        sql[2].sql,
        "ALTER TABLE inventory.items ADD CONSTRAINT pk_items PRIMARY KEY (id)"
    );
    assert_eq!(
        sql[3].sql,
        "CREATE INDEX IF NOT EXISTS inventory.idx_items_name ON inventory.items (name)"
    );
}

#[test]
fn builds_unique_index_sql() {
    let table = Table::new("categories")
        .primary_key("pk_categories", ["id"])
        .index_unique("uq_categories_name", ["name"]);
    let schema = Schema::new("inventory").table(table.clone());

    let sql = create_index(&schema, &table, &table.indexes[0]);

    assert_eq!(
        sql.sql,
        "CREATE UNIQUE INDEX IF NOT EXISTS inventory.uq_categories_name ON inventory.categories (name)"
    );
}

#[test]
fn builds_drop_schema_sql_for_table_and_indexes() {
    let schema = Schema::new("inventory").table(
        Table::new("items")
            .primary_key("pk_items", ["id"])
            .index("idx_items_name", ["name"]),
    );

    let sql = drop_schema_statements(&schema);

    assert_eq!(sql.len(), 4);
    assert_eq!(sql[0].sql, "DROP INDEX IF EXISTS inventory.idx_items_name");
    assert_eq!(
        sql[1].sql,
        "ALTER TABLE inventory.items DROP CONSTRAINT IF EXISTS pk_items"
    );
    assert_eq!(sql[2].sql, "DROP TABLE IF EXISTS inventory.items");
    assert_eq!(sql[3].sql, "DROP SCHEMA IF EXISTS inventory");
}

#[test]
fn defines_persistence_catalog_in_schema_terms() {
    let schema = persistence_catalog();

    assert_eq!(schema.name, "meta");
    assert_eq!(schema.tables.len(), 6);
    assert_eq!(schema.tables[0].name, "schemas");
    assert_eq!(schema.tables[1].name, "tables");
    assert_eq!(schema.tables[2].name, "columns");
    assert_eq!(schema.tables[3].name, "primary_keys");
    assert_eq!(schema.tables[4].name, "indexes");
    assert_eq!(schema.tables[5].name, "index_columns");
    assert_eq!(schema.tables[0].columns[0].name, "id");
    assert_eq!(schema.tables[0].columns[0].data_type, DataType::BigInt);
    assert_eq!(schema.tables[1].columns[1].name, "schema");
    assert_eq!(schema.tables[2].columns[6].name, "ordinal");
    assert_eq!(schema.tables[5].columns[1].name, "index");
}
